baseurl:/myBlog
          |-- _config.yml
          |-- _includes
          |   |-- footer.html
          |   |-- header.html
          |-- _posts
          |   |--2014-01-27-fist.html
          |   |--2014-01-27-hello-jekyll.md
          |-- _layouts
          |   |-- default.html
          |   |-- post.html
          |-- index.html
