markdown: rdiscount
pygments: true
plugins: ./_plugins
paginate: 8

safe: false

#站点基础配置
title: Violet
subTitle: Jekyll blog.
description: 基于 Jekyll 搭建起来的博客。
url: http://anryzhang.github.io/myBlog
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
  - text: 文章归档
    url: /archives.html
  - text: 作品
    url: /works.html
  - text: 联系我
    url: http://www.diy1818.com/a/aboutus/index.html
  - text: 博客源代码
    url: https://github.com/anryzhang/myBlog

#theme config
themes: /themes/violet

#配置你喜欢的顶部背景图片
headimg:
  - item: /themes/violet/images/hdbg01.jpg
  - item: /themes/violet/images/hdbg02.jpg
  - item: /themes/violet/images/hdbg03.jpg
  - item: /themes/violet/images/hdbg04.jpg

#关注我
follow:
  - class: fa-github
    url: http://github.com/anryzhang


#作者信息
author:
  link: http://www.diy1818.com/a/aboutus/index.html

#评论信息
disqus:
  config: true
  id: anryzhang

duoshuo:
  config: false
  id: anryzhang